# CHANGEME: Set these variable to your liking
title: Thermometer Hygrometer mit OLED-Display
description: IoT Thermometer Hygrometer mit OLED-Display. Smarthome-Anbindung via ESPHome / MQTT.
theme: jekyll-theme-slate
